apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\lalim\kompose.exe convert -f C:\Users\lalim\IdeaProjects\jsandbox\docker\postgres\docker-compose.yaml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: adminer
  name: adminer
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: adminer
status:
  loadBalancer: {}
