apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\lalim\kompose.exe convert -f C:\Users\lalim\IdeaProjects\jsandbox\docker\postgres\docker-compose.yaml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    io.kompose.service: db
status:
  loadBalancer: {}
