apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: kafka
  name: kafka-service
spec:
  ports:
    - name: "9092"
      protocol: TCP
      port: 9092
      targetPort: 9092
    - name: "2181"
      protocol: TCP
      port: 2181
      targetPort: 2181
  externalTrafficPolicy: Local
  type: LoadBalancer
  selector:
    io.kompose.service: kafka